import { IEnvironment, IAuth, IApplicationState, IAddress, IAddressType, ICustomer, ILineItem, ITax, IDiscount, IPayment, IPigi, IOrderMetaData, IShipping, ICurrency, IOrderInitialData, ICountryInformation, IGeneralSettings, ISupportedLanguage, IFees } from "..";
export declare const environment: Required<IEnvironment>;
export declare const auth: IAuth;
export declare const pigi: IPigi;
export declare const customer: ICustomer;
export declare const shippingAddress: IAddress;
export declare const billingAddress: IAddress;
export declare const addresses: IAddressType;
export declare const line_items: Array<ILineItem>;
export declare const taxes: Array<ITax>;
export declare const discounts: Array<IDiscount>;
export declare const fees: Array<IFees>;
export declare const payments: Array<IPayment>;
export declare const order_meta_data: IOrderMetaData;
export declare const shipping: IShipping;
export declare const currency: ICurrency;
export declare const display_currency: ICurrency | null;
export declare const countryInfo: ICountryInformation;
export declare const generalSettings: IGeneralSettings;
export declare const supportedLanguages: ISupportedLanguage;
export declare const applicationState: IApplicationState;
export declare const orderInitialData: IOrderInitialData;
export declare const retryErrorCodeList: Array<number>;
export declare const retryErrorCodeWaitTime: Array<number>;
